services:
  - type: web
    name: learnwithorin-www
    runtime: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    # Custom domain configuration (optional)
    # customDomains:
    #   - name: learnwithorin.com
    #   - name: www.learnwithorin.com

    # Build filters for efficient deploys
    buildFilter:
      paths:
        - src/**/*
        - public/**/*
        - package.json
        - yarn.lock
        - vite.config.ts
        - server.js
        - index.html
        - tailwind.config.js
        - postcss.config.js
      ignoredPaths:
        - README.md
        - .env.example
